meta_product_name: "Poochy"
meta_title: "Poochy - Walk dogs, find friends"
meta_description: "Bringing socializing back to the real world with a ton of poochy love"
meta_image: "walker.png" # should exist in `app/assets/images/`
